server:
  port: 10086
spring:
  application:
    name: com.gongli.glRegistry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
    register-with-eureka: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
