spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 321
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host:
  rabbitmq:
    virtual-host:
    host:
    username:
    password:
    template:
      exchange: gongli.sms.exchange
    publisher-confirms: true
server:
  port: 8085
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: com.gongli.user.pojo


