server:
  port: 8081
spring:
  application:
    name: item-service
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 321
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host:
    password:
    username:
    virtual-host:
    template:
      exchange: gongli.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
