server:
  port: 8082
spring:
  application:
    name: upload
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${server.port}
fdfs:
  connect-timeout: 2000
  thumb-image:
    width: 60
    height: 60
  so-timeout: 2000
  tracker-list:
   - 139.196.158.184:22122